### ISSUE TITLE
Separate address input/output

### ISSUE THREAD

**Issue by dacom-dark-sun** [pigochu/yii2-jquery-locationpicker#11]
Hello, my friend! How i can create expression for output/input cities/countries one by one, in different input fields? Output like in this example:
https://i.imgsafe.org/dfdd69d715.jpg

If can create input like that, this is will amazing )

**Comment by pigochu** [comment]
@dacom-dark-sun 

I think you must create ur self.
please read the document's sample from http://logicify.github.io/jquery-locationpicker-plugin/

search  **"Advanced usage of geo decoder features"** in the document.

If u want to do two-way data binding , you can create a feature request to "JQuery Location Picker" author , not me.

I only implement **yii2 widget** , I am not "JQuery Location Picker" author.
