### ISSUE TITLE
How get bower-asset/jquery-locationpicker-plugin.

### ISSUE THREAD

**Issue by PradeepN93** [pigochu/yii2-jquery-locationpicker#12]
When I have update the composer by adding "pigochu/yii2-jquery-locationpicker": ">=0.2.0" in composer.json in my file  , the composer gives an error pigochu/yii2-jquery-locationpicker": ">=0.2.0 requires bower-asset/jquery-locationpicker-plugin.
please suggest me to get the bower-asset/jquery-locationpicker-plugin in my Yii2 file.

**Comment by pigochu** [comment]
Have you ever installed  "fxp/composer-asset-plugin" ? 

~~~
composer global require "fxp/composer-asset-plugin:^1.2.0"
~~~

https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md

**Comment by PradeepN93** [comment]
Yes ,"extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    },
This code is there in my composer.json file
but the composer gives an error, "bower-asset/jquery-locationpicker-plugin" required

Please help me

**Comment by pigochu** [comment]
No idea ... I create a new project for testing ,  no error.
![image](https://cloud.githubusercontent.com/assets/1013744/21800026/bbb42d6a-d756-11e6-8a6c-3f5ea1e37d48.png)

I think you can try update composer-asset-plugin
~~~
composer global update --prefer-dist
~~~
show the lastest version
~~~
D:\projects\rollcall>composer global info
Changed current directory to C:/Users/Pigo/AppData/Roaming/Composer
fxp/composer-asset-plugin v1.2.2 NPM/Bower Dependency Manager for Composer
~~~

v1.2.2 is latest version


or reinstall composer and plugin

1. remove composer
2. remove composer cache folder
3. reinstall fxp/composer-asset-plugin
4. try install yii2-location-picker again
