### ISSUE TITLE
Custom Expression

### ISSUE THREAD

**Issue by deshario** [pigochu/yii2-jquery-locationpicker#19]
How can I get the more values by custom expression ... Currently i can access only latitude and longtitude  .... I had print the object in console that gets from onchanged ... it has only latitude and longtitude ... I'm trying to access more data such as full address .. How can i do that ? #Thankx

![new1](https://user-images.githubusercontent.com/11426727/41522049-b9ad0e48-72fe-11e8-9e70-6053e3ad01b5.PNG)
![new2](https://user-images.githubusercontent.com/11426727/41522051-bd348c8a-72fe-11e8-921a-d66ade97d622.PNG)

**Comment by pigochu** [comment]
You can not get searchBox value from server ?

I think you could create a hidden input , than implement js onsubmit event and copy searchbox value to your hidden input.

If you want to get more info from server. you can use Geocoding API .
https://developers.google.com/maps/documentation/geocoding/intro.

**Comment by pigochu** [comment]
you can also read how to Binding UI with the widget , than implement inputBinding  map to your hidden input.
http://logicify.github.io/jquery-locationpicker-plugin/

**Comment by pigochu** [comment]
@deshario 
in onchanged event , you can use addressComponents.
var addressComponents = $(this).locationpicker('map').location.addressComponents;

**Comment by deshario** [comment]
There are only 4-5 attributes that can be accessible  from addressComponents  ...  It will be great if we can access full address. Thankx

**Comment by pigochu** [comment]
@deshario 

I dont understand  fulladdress what you want , but I can get full address from formattedAddress.

![image](https://user-images.githubusercontent.com/1013744/41565436-5b590ab4-7389-11e8-982f-ca61070c3e08.png)
