### ISSUE TITLE
SearchBox Issue

### ISSUE THREAD

**Issue by deshario** [pigochu/yii2-jquery-locationpicker#20]
How to update marker after select a place from searchbox ... It's not updating the marker in the map until i not remove `inputBinding`

>  'inputBinding' => [
                    'latitudeInput'     => new JsExpression("$('#us2-lat')"),
                    'longitudeInput'    => new JsExpression("$('#us2-lon')"),
                    'radiusInput'       => new JsExpression("$('#us2-radius')"),
                    'locationNameInput' => new JsExpression("$('#us2-address')")
                ],

But if i remove `inputBinding` .... it works ... Do we need to remove `inputBinding` to make searchbox works

![screenshot 276](https://user-images.githubusercontent.com/11426727/41777505-bf572e8c-7655-11e8-9892-9ff8f4e2d137.png)

**Comment by pigochu** [comment]
If you don't need inputBinding , you can remove it.

if you need inputBinding , you should remove locationNameInput. because locationNameInput default map to searchbox.
