### ISSUE TITLE
Remove Default Value

### ISSUE THREAD

**Issue by deshario** [pigochu/yii2-jquery-locationpicker#25]
How can i remove default value of campaign_coordinates ... I wanna make user select manually ... In this case .. either user dont select location ... it will be default value ... I wanna show error message below the campaign_coordinates field if user dont select location.

![remove22](https://user-images.githubusercontent.com/11426727/42410523-33ae7626-8215-11e8-8c0a-7fb965434b9a.PNG)

![remove](https://user-images.githubusercontent.com/11426727/42410513-0a758bf0-8215-11e8-877e-373a78fc9d15.PNG)

**Comment by deshario** [comment]
https://github.com/pigochu/yii2-jquery-locationpicker/issues/5#issuecomment-266165174

I clear default value like this : 

> document.getElementById('campaigns-campaign_coordinates').value = '';

Is it possible to hide default marker also ... how can we do that

**Comment by pigochu** [comment]
@deshario 

please read google map document

https://developers.google.com/maps/documentation/javascript/examples/marker-remove

You can get google map instance , ex: var map = $("your-coordinates-id').locationpicker("map").map;
