### ISSUE TITLE
Name labels

### ISSUE THREAD

**Issue by arjenmeijer** [pigochu/yii2-jquery-locationpicker#3]
Greetings from Holland,

around the map there are labels for the field name.
I.e. if I start with echo $form->field($model, 'gps')->widget
the widget begins in bold Gps, new line, than the map, new line, and closes with Gps in gray.
Is there a way to remove the Gps words from the form?

**Comment by pigochu** [comment]
try $form->field($model, 'gps')->widget( ... ).label(falsE);

**Comment by arjenmeijer** [comment]
]).label(false);

Call to undefined function label()

**Comment by pigochu** [comment]
sorry My mistake  ... change to "->label(false)" , ha ha

**Comment by arjenmeijer** [comment]
Thanks, this removes the bold Gps label in front, but leaves the grey Gps label after the map.

**Comment by pigochu** [comment]
impossioble , I havnt write any code about grey label. maybe you wrote method  "->hint('...')" , so it display hint string .
Can you post your php code and html code ?

**Comment by arjenmeijer** [comment]
You are correct. It is a hint problem. This solves it:
])->label(false)->hint(false);
