### ISSUE TITLE
Coordinates not back to model

### ISSUE THREAD

**Issue by dacom-dark-sun** [pigochu/yii2-jquery-locationpicker#5]
I use example for back coordinates to model, but always receive a null. Code:
```
<?php echo $form->field($model, 'coordinates')->widget('\pigolab\locationpicker\CoordinatesPicker' , [
        'key' => 'my_key_here',
        'valueTemplate' => '{latitude},{longitude}' ,
        'options' => [
            'style' => 'width: 100%; height: 400px',  // map canvas width and height
        ] ,
        'searchBoxOptions' => [ // searchBox html attributes
            'style' => 'width: 300px;', // Optional , default width and height defined in css coordinates-picker.css
        ],
        'mapOptions' => [
            // google map options
            // visit https://developers.google.com/maps/documentation/javascript/controls for other options
        
            
        ],
      'clientOptions' => [
            'location' => [
                'latitude'  => 46.15242437752303 ,
                'longitude' => 2.7470703125,
            ],
            'radius'    => 300,
            'inputBinding' => [
                'latitudeInput'     => new JsExpression("$('#us2-lat')"),
                'longitudeInput'    => new JsExpression("$('#us2-lon')"),
                'radiusInput'       => new JsExpression("$('#us2-radius')"),
                'locationNameInput' => new JsExpression("$('#us2-address')")
            ]
]      
    ]);
?>
 

```
In model:
`
...
{
  public $coordinates;
..
..
`
What problem can be here?

**Comment by pigochu** [comment]
Could you post your mysql table schema and model class source code ?

**Comment by dacom-dark-sun** [comment]
Im sorry for long answer, but actually it is my mistake with validation rules. Your widget words perfectly, but one question more: 
How i can bind click event for get coordinates, that use not use drag and drop principle?

**Comment by pigochu** [comment]
@dacom-dark-sun 

it's very easy, you can get the hidden input value 

![image](https://cloud.githubusercontent.com/assets/1013744/21069726/6ebb21ce-beb7-11e6-8906-7d442e1b1e36.png)

~~~javascript
alert($('#locationpicker-coordinates').val() );
~~~

**Comment by pigochu** [comment]
@dacom-dark-sun 

Oh . . I misunderstand what you mean

I need read jquery-locationpick or google map document how to do that

**Comment by pigochu** [comment]
Try it
~~~php
    $js = '
    function(c){
        var map = jQuery(c).locationpicker("map").map;
        google.maps.event.addListener(map, "click", function(e) {
            var marker = jQuery(c).locationpicker("map").marker;
            var pos = e.latLng;
            jQuery(c).locationpicker("location" , {latitude: pos.lat(), longitude: pos.lng()});
            google.maps.event.trigger(marker, "dragend");
            // e.stopPropagation();
          });
    };
~~~


then in the  CoordinatesPicker  add oninitialized event
~~~php
        'clientOptions' => [
            'addressFormat' => 'street_number',
            'radius'    => 300,
            'oninitialized' => new JsExpression($js),
        ],
~~~

**Comment by dacom-dark-sun** [comment]
Ok, thank you very much!) i will try it ASAP.. 

Can i disable auto-render default location? 
For.. not render any markers by default, but if user click or choice some place, model must receive coordinates.. Cause not every place need mark location from user, but if we have default position, this is can create some confusion..

**Comment by pigochu** [comment]
I think it possible ,

Options has a "markerVisible" can be set to false.

You can read all options from document http://logicify.github.io/jquery-locationpicker-plugin and try to implement your event.

**Comment by dacom-dark-sun** [comment]
Thanks a lot, i was solve it: 
 jQuery(c).locationpicker("map").marker.visible = true;
and load by default with false.
